name: Nest.js CI

on:
  push:
    branches: [ "main" ]


jobs:
  run-dev:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - run: cd backend && echo "${{ secrets.ENV_FILE }}" > .env
    - run: cd backend && npm i
    - run: cd backend && npm run build
